//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRegistry
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int ProductionYear { get; set; }
        public string Engine { get; set; }
        public string Transmission { get; set; }
        public string Condition { get; set; }
        public int DistanceTraveled { get; set; }
        public int Price { get; set; }
        public string LicensePlateNumber { get; set; }
        public string Location { get; set; }
        public string PhoneNumber { get; set; }
    }
}
